import { StyleSheet, Dimensions } from 'react-native';
export default styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'black',
  },
  background: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: Dimensions.get('screen').height,
  },
  central_block: {
    display: 'flex',
    flexDirection: 'row',
    marginVertical: 12,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height * 0.15,
    justifyContent: 'space-around',
    overflow: 'hidden',
  },
  central_text: {
    fontSize: Dimensions.get('window').width * 0.062,
    margin: 2,
    opacity: 0.9,
    color: 'black',
    fontWeight: '700',
    textShadowRadius: 2,
    textShadowColor: 'black',
  },
  central_date: {
    fontSize: 11,
    margin: 0,
    textShadowRadius: 2.5,
    textShadowColor: 'black',
  },
  linear: {
    padding: 5,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    height: '100%',
    width: Dimensions.get('window').width * 0.47,
    borderRadius: 12,
    textAlign: 'center',
    justifyContent: 'space-around',
    alignContent: 'center',
  },
  logos: {
    position: 'relative',
    height: '60%',
    width: '48%',
    opacity: 1,
  },
  text: {
    fontSize: 13,
    marginBottom: 10,
    color: '#F5ECCE',
    fontWeight: 'bold',
    textShadowRadius: 11,
    textShadowColor: 'black',
  },
  header: {
    top: 8,
    left: 0,
    right: 0,
    color: '#F5ECCE',
    fontWeight: 'bold',
    fontSize: 14.1,
    textAlign: 'center',
    position: 'absolute',
    zIndex: 1,
    textShadowRadius: 7,
    textShadowColor: 'black',
  },
  valueContainer: {
    minHeight: '60%',
    width: '45%',
    borderRadius: 16,
    borderWidth: 1.4,
    borderStyle: 'dashed',
    borderColor: '#4C4C4C',
    opacity: 0.8,
    alignItems: 'center',
  },
  refreshButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 12,
    width: Dimensions.get('window').width * 0.97,
    height: Dimensions.get('window').height * 0.05,
    backgroundColor: '#519600',
    borderRadius: 16,
  },
  buttonText: {
    color: '#F5ECCE',
    fontWeight: 'bold',
    textShadowRadius: 11,
    textShadowColor: 'black',
  },
});
